### ISSUE TITLE
duplicate bike_ped datasets

### ISSUE THREAD

**Issue by laurenengelwilder** [psrc/data-portal-tools#40]
which one should be on the portal? do they both need to exist? you own them both

**Comment by laurenengelwilder** [comment]
I'm going to remove these for now. I think there were other bike ped datasets that transportation wanted up. But still it'd be great to clean these up if they're redundant,

**Comment by christopeak** [comment]
Verified that neither existing layer was referenced in web amps, then removed both and re-published.
