### ISSUE TITLE
tribal lands metadata is wrong

### ISSUE THREAD

**Issue by laurenengelwilder** [psrc/data-portal-tools#45]

**Comment by christopeak** [comment]
Fixed.

**Comment by laurenengelwilder** [comment]
The metadata needs editing. It refers to WSDOT not being responsible for blah blah blah. I might make some quick changes for now, but we'll need to get this rewritten by Drew.

**Comment by christopeak** [comment]
For posterity: the source of that WSDOT-not-responsible language was from the layer's entry in the metadata form.  We can certainly edit that.
