### ISSUE TITLE
publish transit routes and stops 2018 versions

### ISSUE THREAD

**Issue by laurenengelwilder** [psrc/data-portal-tools#73]
these still need metadata, but let's get them publsihed.
Database Connections\ElmerGeo_sde.sde\ElmerGeo.DBO.rtp_2022\ElmerGeo.DBO.transit_routes_2018_rtp
Database Connections\ElmerGeo_sde.sde\ElmerGeo.DBO.rtp_2022\ElmerGeo.DBO.transit_stops_2018_rtp

**Comment by christopeak** [comment]
Who should I put down as the staff contact for these?

**Comment by christopeak** [comment]
Titling these "Transit_Routes_2018_RTP" and "Transit_Stops_2018_RTP" for now.  Would love to come up with a better layer name.

**Comment by christopeak** [comment]
exported.

**Comment by christopeak** [comment]
There are already two layers on Arc Online _Transit_Stops_2018_ and _Transit_Routes_2018_, both owned by Kalon.  Not sure if these are the same as what I just published.

**Comment by christopeak** [comment]
Stefan says that the versions of these currently in ElmerGeo are not the most up to date, and that we should use Kalon's _Transit_Stops_2018_ and _Transit_Routes_2018_ for the Portal.  @laurenengelwilder could you either add the appropriate categories to those or transfer ownership of the layer from Kalon to me so that I can do that?

**Comment by laurenengelwilder** [comment]
I'm very confused by these. I think for these we don't want the most up to date, but what was used for the RTP. I might need to follow up with Kalon about what they want to have on the portal.

**Comment by christopeak** [comment]
Good point.  I think your confusion comes from my misstating that the ElmerGeo versions are less up to date when I really meant they were not what was used for the RTP (despite the fact that they have the suffix "_RTP" in their title).  It sounds like Transportation staff have gone to some lengths to make sure the layers they are showing in RTP-supporting web maps are Kalon's versions currently in Arc Online, not the ones in ElmerGeo.

**Comment by christopeak** [comment]
I'll summarize my understanding in a Teams channel and try to get Stefan to verify concurrence, so that we can all make sure we are on the same page on this.

**Comment by christopeak** [comment]
Closing this issue again, since Stefan and Kalon have now agreed that the layers I had originally uploaded from ElmerGeo are indeed the correct ones after all.
