### ISSUE TITLE
wrong equity tract metadata

### ISSUE THREAD

**Issue by laurenengelwilder** [psrc/data-portal-tools#88]
There are two layers that are "equity tracts", and this one should include opportunity index metadata, but seems to have the metadata for the rtp equity layer.

https://psrc-psregcncl.hub.arcgis.com/datasets/PSREGCNCL::opportunity-index-equity-tracts/about

**Comment by laurenengelwilder** [comment]
Brian is tasked with writing it up now. so i guess we should erase it for now and then update with brian's metadata when that's done.

**Comment by christopeak** [comment]
Also the current layer doesn't conform to our new naming conventions (capitalize words in the layer name).  I will re-publish with the new format.

**Comment by christopeak** [comment]
Exported, with capitalized title.
